# Generated by Django 6.0.4 on 2026-04-22 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ember_rootapp', '0003_menuitem_pizza_recommended_pairing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='read_by_user',
            field=models.BooleanField(default=False),
        ),
    ]
