# Generated by Django 6.0.4 on 2026-04-22 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ember_rootapp', '0004_contactmessage_read_by_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='recommended_pairing_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pizza',
            name='recommended_pairing_image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
